# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81ab173d80255c771775670fe270ab7a884c4d7eacd1caed9b923ac36dc1f8592b763c773608f0b1b256ad327c62133b147778f227bbf1b18a5b94dd4d9180d4

test:
  secret_key_base: 0bafe20c5e9a22ebe393cb74ba60280988310412a9769945d6ba2acace1726e232f93f2a34a2d8847fd0355625b56cb4be51d85921135aa64f9fbe824e7b7ae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
